export const metadata = {
  title: 'Settings | Dashboard - LiveTraders',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body>{children}</body>
    </html>
  )
}
