import Script from "next/script";
import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Homepage - LiveTraders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <script
        src="//code.tidio.co/c6nluhrmfkhxdaohcp72oinplmluyjaz.js"
        async
      ></script>
      <Script
        charset="UTF-8"
        type="text/javascript"
        src="/js/a2834ccd-f585-40c4-a580-fc072f9479e0.js"
      />
    </html>
  );
}
